plone/meta

- config/default/pyproject.toml.j2
> More towncrier sections

- config/config-package.py
> No parallel tox

- config/config-package.py
- config/default/packages.txt
- config/default/pyproject.toml.j2
- config/default/tox.ini.j2
Closes #29 
Used in https://github.com/plone/plone.session/pull/34
> Allow codespell ignore words

- config/default/lint-requirements.txt.j2
- config/default/tox.ini.j2
Closes #28 
This time I tested it before pushing 🤞🏾 🍀 
@mauritsvanrees as on your examples you did add `-n 10` I went with it 👍🏾
> feat: another linter (pyroma)

- config/default/lint-requirements.txt.j2
- config/default/packages.txt
- config/default/tox.ini.j2
Closes #33 
See it in action on https://github.com/plone/plone.app.caching/pull/113 although there it does _nothing_ as it was already being applied 😅 it does not change anything, which means that it runs fine 🍀
> feat: format XML files with zpretty

- config/default/lint-requirements.txt.j2
- config/default/packages.txt
- config/default/tox.ini.j2
Closes #14 
Again, like `z3c.dependencychecker`, it is not run by default, maybe we could run it on a weekly basis, or on demand? 🍀 🤔 
@davisagli idea of embedding it on the job summary is a nice one as well, we could see if it makes sense.
> Dependency graph

- README.md
Maybe we want to move that somewhere else, but meanwhile, better documented here than nowhere 🙈
> feat: add docs on this repository purpose and usage

- config/default/pre-commit-config.yaml
> fix: add toml dependency to codespell

- config/default/tox.ini.j2
Requires tox 4.4.0+.
See https://github.com/plone/plone.app.z3cform/pull/162#issuecomment-1479461619
> Use constrain_package_deps = true.

- config/default/pyproject.toml.j2
https://github.com/zopefoundation/ExtensionClass/tree/master/src
> Add own namespaces from package ExtensionClass

- config/config-package.py
- config/default/coverage.yml.j2
⚠️ This needs discussion ⚠️ 
See https://github.com/plone/meta/issues/87 for the rationale.
See this [`plone.batching` PR](https://github.com/plone/plone.batching/pull/48) as a reference implementation on what that actually means
> Add coverage workflow on repositories

- config/config-package.py
- config/default/editorconfig.j2
- config/default/packages.txt
- config/default/pre-commit-config.yaml.j2
- config/default/setup.cfg.j2
- config/default/tox.ini.j2
Part of #82 
After scratching my head over and over about how to solve the problem, we (me @mauritsvanrees , @jensens and @ericof ) came with the idea of adding extension points to all files, as much as needed, but rather than going to the very specific details, allow these extensions points to be dumb, i.e. a plain multiline string in TOML that gets printed on the configuration files ✨
> Options everywhere

- config/config-package.py
- config/default/changelog_template.jinja
- config/default/pyproject.toml.j2
And configure towncrier accordingly.
Closes #49
> feat(towncrier): detect CHANGES file format

- config/default/pre-commit-config.yaml.j2
> feat: add i18ndude integration

- config/default/tox.ini.j2
Fixes https://github.com/plone/meta/issues/110
> Fix coverage by only covering the source of the package_name.

- config/default/editorconfig.j2
> Update .editorconfig to also have sane frontend configuration.

- config/default/gitignore.j2
Added `node_modules/` and fixed sectionname in comment to add `extra_lines`
> Update `.gitignore` defaults

- config/README.md
- config/config-package.py
- config/default/pyproject.toml.j2
> Allow to extend all pyproject.toml sections

- config/README.md
- config/config-package.py
- config/default/tox.ini.j2
Specially for collective, or internal usage within companies, that is a must.
Generating the right constraints file can be tricky, and by all means is out of scope of `plone/meta` to generate it for you 😅 
But maybe some guidelines could be used, or pointing to tools (pip-tools, poetry...) can be useful? 🤔 
Closes #136
> Custom constraints file

- config/README.md
- config/config-package.py
- config/default/tox.ini.j2
> Tox test environment variables

- config/README.md
- config/config-package.py
- config/default/meta.yml.j2
> Add options to configure .github/workflows/meta.yml

- config/config-package.py
- config/requirements.txt
See https://github.com/plone/meta/issues/154#issuecomment-1615182604 for details
> Some issues found on fresh install and configuring a collective package generated with `bobtemplates.plone`

- config/config-package.py
- config/default/pre-commit-config.yaml.j2
> added missing line 

- config/README.md
- config/config-package.py
- config/default/pyproject.toml.j2
- config/default/tox.ini.j2
- news/170.feature
> Create towncrier config conditionally on existing `news/` folder.

- .github/workflows/test.yml
- news/180.bugfix
> Avoid broken windows GHA

- config/README.md
- config/config-package.py
- config/default/tox.ini.j2
- news/185.feature
> Customize tox testenv

- config/config-package.py
Handle a bit nicer the markdown/rst differences.
> Towncrier fixups

- config/config-package.py
- config/default/dependabot.yml
- news/201.feature
> Dependabot updates

- config/default/gitlab-ci.yml.j2
To speed up CI.
We need to do that in GHA as well, contributions welcome 😄
> feat(gitlab): cache pre-commit repositories

- config/default/pyproject.toml.j2
> feat(dependencies): add pytest-plone mapping

- .editorconfig
- .flake8
- .github/dependabot.yml
- .github/workflows/local.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/plone/meta/config_package.py
- src/plone/meta/multi_call.py
- src/plone/meta/re_enable_actions.py
- src/plone/meta/shared/call.py
- src/plone/meta/shared/git.py
- src/plone/meta/shared/packages.py
- src/plone/meta/shared/path.py
- src/plone/meta/shared/utils.py
- tox.ini
Add, more or less, the same tooling that `plone.meta` enforces on the distributions it configures.
To keep consistency and developer experience :)
It needs merging #249 first.
> QA tooling
