plone/meta

config/default/setup.cfg.j2
There is no real benefit of havign `tox.ini` in releases, tell `check-manifest` to ignore it :-)
Closes #5
=> fix: ignore tox.ini on releases

config/default/lint-requirements.txt.j2, config/default/tox.ini.j2
Add a new tool on `tox.ini` `lint` section: check-manifest.
This tool reports if there are any mismatch with the git checkout and what would go on a release.
This helps to avoid the so called _brown bag releases_.
Closes #6
=> feat(tox): install and run check-manifest

config/default/tox.ini.j2
To use a more powerful/better way to get the files that need to be passed to formatters or linters.
Closes #11
=> feat(tox): use git ls-files

config/config-package.py
This is a safe belt to allow users to verify and tweak the changes before pushing them.
Closes #3
=> feat: do not push new configuration by default

config/config-package.py
We still passed self.config_type, which was interpreted as meta_hint, so at the top of the generated setup.cfg we got a string 'default', giving it a bad syntax. Fixes https://github.com/plone/meta/issues/23
=> Fix setup.cfg rendering.

config/config-package.py, config/default/packages.txt, config/default/setup.cfg.j2, config/shared/toml_encoder.py, config/shared/utils.py
Insert these in setup.cfg.
Fixes https://github.com/plone/meta/issues/24
This PR is based on the (much smaller) branch from PR #25.
Sample contents of `.meta.toml`:
```
[setup.metadata]
long_description = "file: README.rst, CHANGES.rst"
classifiers = """
Development Status :: 5 - Production/Stable
Environment :: Web Environment
Framework :: Plone
"""
[setup.options]
include_package_data = true
zip_safe = false
packages = [
]
python_requires = ">= 3.8"
install_requires = """
setuptools>=36.2
plone.app.caching
plone.app.iterate
plone.app.upgrade
plone.restapi
plone.volto
Products.CMFPlacefulWorkflow
Products.CMFPlone
"""
```
Resulting setup.cfg is:
```
[metadata]
long_description = file: README.rst, CHANGES.rst
classifiers =
Development Status :: 5 - Production/Stable
Environment :: Web …
```
=> Support setup.metadata and setup.options in .meta.toml.

config/README.rst, config/config-package.py, config/default/lint-requirements.txt.j2, config/default/pyproject.toml.j2, config/default/tox.ini.j2
Closes #12 
See it in action on https://github.com/plone/plone.batching/pull/35 and https://github.com/plone/plone.subrequest/pull/28
For now I added it as a new `dependencies` `tox` environment that is not run by default.
Should we do that at some point though? 🤔 🍀
=> Configure z3c.dependencychecker

config/README.rst, config/config-package.py, config/default/linting.yml.j2, config/default/tests.yml.j2, config/default/tox.ini.j2
Run distributions' tests on on GitHub Actions 🎉 
Not enabled by default, a new option must be set on `.meta.toml` so that this is enabled.
The `tox` sections is created nonetheless, so even if not enabled, one can check if it does work or not 🍀
=> Configure testing

config/config-package.py, config/default/packages.txt
Saw this when handling plone.releaser:
fatal: pathspec 'filename' did not match any files
=> Fix removing old files.

config/default/tox.ini.j2
If no files are given `zpretty` breaks.
Until https://github.com/collective/zpretty/issues/97 is fixed and released 😄
=> fix: avoid zpretty error

config/default/packages.txt, config/default/tox.ini.j2
Rather than having two of them, a single one with all the tools, that anyway revolve around the same topic sounds better resource wise
=> Merge tox dependencies environments

config/default/packages.txt, config/default/tox.ini.j2
With these changes, it _should be possible_ ™️ to mass-enable all repositories to run tests.
Note that the GitHub workflow to run tests is configured centrally on plone GitHub's organization.
=> Enable tests always

config/default/packages.txt, config/default/pyproject.toml.j2
Closes #52 
With this, when configuring a package, we don't need to list all its dependencies, but can hide quite a few of them with `plone.base`.
Should we do the same with `Zope`, here technically we need a mapping, as `Zope` provides quite a few random namespaces (`OFS`, `ZTUtils`, a few `Products.`, `Testing` ...).
Another candidate to get added on the `plone.base` could be `setuptools`, there is no need to keep it on all and every single distribution, right?
Specially with the idea that it is less and less important to mention it...
__Edit:__ and now I see #52 😅
=> Plone base dependency

config/default/pyproject.toml.j2
When I run the coredev buildout I now get this:
```
Develop distribution: plone.portlet.static 4.0.1.dev0
uses namespace packages but the distribution does not require setuptools.
Develop distribution: plone.portlet.collection 4.0.1.dev0
uses namespace packages but the distribution does not require setuptools.
Develop distribution: plone.z3cform 2.0.1.dev0
uses namespace packages but the distribution does not require setuptools.
Develop distribution: plone.app.querystring 2.0.2.dev0
uses namespace packages but the distribution does not require setuptools.
```
It is a [warning from buildout](https://github.com/buildout/buildout/issues/526).
It seems to work, but I don't trust it.
See same comment I made in the [PR that added this](https://github.com/plone/meta/pull/59#issuecomment-146891793 …
=> Do not ignore setuptools when plone.base is installed.

config/README.rst, config/config-package.py, config/shared/git.py
For example:
```
bin/python config-package.py --branch current ../../6.0/src/plone.portlets
```
Use case:
1. Configure a package, make a PR.
2. Discover a problem, fix it in `plone/meta`.
3. Configure the package again.
4. You now have two branches called `config-with-default-template-something` and get confused: which was the right one?
So in step 3 you call with with `--branch current` and your current branch gets updated with new commits.
=> Allow updating the current branch.

config/default/tox.ini.j2
To report how much the package is actually being tested.
As @davisagli mentioned (I can't remember where 😓 ) it would be great to have that as part of GitHub Actions artifacts/report that one can build...
Closes #45
=> Add coverage

config/default/pyproject.toml.j2
In order to reduce dependencies to declare, define `Zope` with all dependencies, add `Products.CMFCore` with its dependencies and correctly define `plone.base`. Use transitive dependencies here. It seems like `dependencychecker` correctly interprets them. 
At some point we want to declare this for `Products.CMFPlone` as well, but not now.
This closes #58.
=> Declare all Zope, CMFCore and plone.base dependencies

shared-workflows/tests.yml
... that are being used to run the GHA workflows in.
The default stays the same, only python 3.11, but a repository might want to enforce a set of python versions.
For that one has to override the `TEST_PYTHON_VERSIONS` on the repository variables.
=> Let repositories define the python versions

config/config-package.py, config/default/pyproject.toml.j2
example `.meta.toml`:
```
[codespell]
skip = "*.map,*.zcml"
```
=> Implement `skip` to codespell configuration

README.md, config/default/tox.ini.j2
Closes #84 
Not sure if we want to _pin_ `build` version. They are on version `0.10.0` which does not seem terribly stable to me 😅 
As long as we don't start running it on CI we might need to pin it. And looking at past releases they don't do that many releases either, 3 releases (0.8, 8.9 and 0.10) within 2022 and 2023.
I used the long form of the command line options to make it more readable 🍀 
And as the idea is only to get the `egg-info` building only the `sdist` is probably enough, otherwise it builds both `sdist` and `whl` and with one is more than enough.
=> Smaller dependency tox environment

.github/workflows/coverage.yml, config/default/tox.ini.j2
Part of #72 
Create a _reusable workflow_ that runs `tox -e coverage` and redirects the output to this magic `$GITHUB_STEP_SUMMARY` variable that allows one to create [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). 🎉 
I'm merging it, otherwise I can not test it 😅
=> feat(gha): show coverage report in job summaries

config/config-package.py
I'm not finding it much useful to get tox to run `format` and `lint` environments when configuring a new package, I stash and drop the changes and start anew anyways.
=> feat: do not run tox by default

config/default/setup.cfg.j2
`wheel` by default, in python 3, already creates a python 3 only wheel archive, there is no need to keep the configuration around.
Part of #56
=> cleanup(setup.cfg): remove bdist_wheel section

.github/workflows/release_ready.yml, config/default/meta.yml.j2, config/default/tox.ini.j2
Use `towncrier` and `twine` to ensure that a PR will produce a ready to release artifact.
This way we lower release managers efforts.
Closes #98
=> feat(workflows): check release readiness

.github/workflows/circular.yml, config/default/meta.yml.j2, config/default/tox.ini.j2
Now that @jensens and friends ironed all(?) dependency cycles, is time to ensure that we do not regress on that ⛓️ 
With `pipforester` we can detect those cycles, if the distribution declares all dependencies, and return an error on a GitHub Action ✨ 
Closes #77
=> Enforce no dependency cycles

config/default/pre-commit-config.yaml.j2
Add another linter on `pre-commit`: https://pypi.org/project/check-python-versions/
It checks that all python versions specific across the repository are consistent.
For now, we only check it on `setup.py` and `pyproject.toml` as we are not adding on `tox.ini` all python versions, as we already have Jenkins for that, at least for now.
Closes #44
=> feat(pre-commit): check python versions

config/config-package.py, config/default/gitignore.j2
The entries in `.gitignore` are the most comment ones that I found doing a `cat */.gitignore | sort | uniq -c | sort -g` on all plone/zope packages inside `buidlout.coredev/src` 🍀 
Do I miss anything? JS/CSS ignores? 🤔 
Closes #62
=> feat: add a .gitignore file

config/default/tox.ini.j2
Do this by defining a standard testenv that fails. Other test envs always have to override the commands.
To fail fast, we set `skip_install = true`.
Since the other test envs also take over all settings from this standard testenv, we need to set `skip_install = true` in a few of them. Note that `use_develop = false` is already the default.
Use case: I either thought I knew, or guessed that the `circular` env was actually called `cyclic`.
Before:
```
$ tox -e cyclic
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /Users/maurits/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_editable> python …
```
=> Tox: fail when env is not defined.

config/default/tox.ini.j2
It is already generated on the previous step.
=> fix(tox/circular): do not print the full graph

config/config-package.py, config/default/pre-commit-config.yaml.j2
That's a direct requirement to configure `plone.resource` with `plone/meta` in a clean way.
In `plone.resource` they want to exclude a file and do it so in `pre-commit` configuration.
This PR allows to express such a configuration. 🎉 🍀
=> feat(pre-commit): allow extra configuration on zpretty

config/config-package.py, config/default/tox.ini.j2
Some packages, like `plone.app.textfield` have `tests` rather than `test` as its extra key to define what needs to be installed for running the tests.
Allow, in general, to configure `tox`'s `test` and `coverage` environments.
See it in https://github.com/plone/plone.app.textfield/pull/53
=> feat(tox): allow to install extra dependencies

config/README.md, config/config-package.py, config/default/tox.ini.j2
On the target repository, add to `.meta.toml`:
```toml
[test]
runner = "pytest"
path = "/tests"
```
And re-configure the repository.
Closes #120
=> Implement support for pytest in tox.ini

config/default/tox.ini.j2
I was expecting the default to be `True`, but the documentation clearly says that you have to enable it:
https://coverage.readthedocs.io/en/7.2.7/branch.html
@ericof would you do a corresponding PR to add (if needed) branch coverage also to `pytest`?
=> Do branch coverage

config/config-package.py, config/default/pyproject.toml.j2
I got an error during the release of `plone.app.caching`: https://github.com/plone/plone.app.caching/commit/da68783f2e9ef08dc9f7c86e8f370f446ce681dc
=> Add a dot to news/.changelog_template.jinja

config/default/tox.ini.j2
This way, if your CI tooling parses it, you can directly point it to `tox -e coverage` and you will have your XML report :-)
=> Generate coverage XML reports

config/README.md, config/config-package.py, config/default/pre-commit-config.yaml.j2
Or generally, allow any configuration on `pre-commit` for `flake8` 🍀 
By default it does not add any so far, but we prepare ourselves for it in the future 👍🏾 
Closes #71
=> flake8 plugins

config/README.md, config/config-package.py, config/default/pyproject.toml.j2
[towncrier](https://pypi.org/project/towncrier) supports setting a format for issues (to convert the issue number into a link pointing to the original issue), but it is not possible to use it with `plone/meta`.
This PR adds a `towncrier_issue_format` configuration option:
```toml
[pyproject]
towncrier_issue_format = "[#{issue}](https://github.com/plonegovbr/plonegovbr.portal/issues/{issue})"
```
Implements #147
=> Support setting towncrier issue_format

.github/workflows/coverage.yml, .github/workflows/test.yml, config/README.md, config/config-package.py, config/default/gitlab-ci.yml.j2, config/default/meta.yml.j2
Closes #65 
And with today's addition, we also support GitLab, not only GitHub Actions 😄 
That's going to be a bit of a _maintenance burden_ to keep two CI systems in sync... hopefully we have enough contributors for each that the maintenance is not that much 🍀
=> Allow to install OS dependencies

config/README.md, config/config-package.py
The idea of `plone/meta` and originally from `zopefoundation/meta` is to keep track of all configured packages in a file (`defaults/packages.txt` in `plone/meta`).
With this file, then you can use it with the `multi-call.py` script to mass re-configure all packages that are listed there. 🚀 
That's the desired behavior for plone/collective upstream packages, but not so much for private/forked packages 😅 
@ericof that's going to be really useful specially for companies, or maybe even collective packages that we don't want to keep them in the list of tracked projects. ✨ 🍀
=> Do not track packages

config/README.md, config/config-package.py, config/default/meta.yml.j2, news/164.feature
To set environment variables to be used by all jobs,
specify the following key:
```toml
[github]
env = """
debug: 1
image-name: 'org/image'
image-tag: 'latest'
"""
```
=> Allow setting gha environment variables

config/default/editorconfig.j2, news/1.bugfix
When using `prettier` to format JS code within a repository that has also been configured with `plone/meta`, the line length is turned off (global setting in this editorconfig file) and prettier follows that, thus concatenating lots of strings, that up until before, where following `prettier` default: 80 characters.
=> fix: adjust editorconfig for prettier

config/shared/git.py, news/1.feature
Based on https://github.com/zopefoundation/meta/pull/202
The main benefit here is that when pushing updates on multiple
repositories the branches are all the same, making it easier to
see that they are based on the same changes.
=> Use commit from meta (to create the branch name)

config/README.md, config/config-package.py, config/default/tox.ini.j2, news/155.feature
Closes #155 
Rather than a setting that needs to be set up on `.meta.toml` we try to detect if the package needs it.
Hopefully the package uses the dependency checker tool, and thus, the dependency on `plone.app.robotframework` can be easily spotted ✨
=> Playwright tests

config/default/pyproject.toml.j2, config/default/tox.ini.j2, news/172.feature
Also, build the package in isolation, so the build is free to use the required `setuptools` version. This combination fixes possible `ModuleNotFoundErrors` for `plone.app.*` packages. See https://github.com/plone/meta/issues/172
=> In pyproject.toml, add build-system requiring setuptools 68.2+.

config/README.md, config/default/editorconfig.j2, news/197.internal
- Add an xml type to the xml section.
- Move the HTML type to the xml section.
This allows more easily for frontend related files except HTML files to be
reconfigured for an 4-space indentation. 4 spaces for JS/CSS related code is
the default style in Patternslib/Mockup. style.
Fixes: #197
=> Editorconfig: Restructure the frontend config.

config/config-package.py, config/requirements.txt
Fixes #194 and #153
After configuring the target repository, check that the generated files are still valid TOML/ini/YAML files.
It would be shameful to re-configure a distribution and leave it in a broken state 😓
=> Validate files

config/default/editorconfig.j2, news/208.bugfix
Reason: https://spec.editorconfig.org/#no-inline-comments
Fixes #207
=> Moved comments in .editorconfig to their own lines

.github/workflows/test.yml, news/210.bugfix
Avoid depending on `vars.*` variables defined at GitHub repository or organization level to run the test job.
We need a way to define which python and OS combinations each repository wants to use, but not defined in a global way, that by default, is broken for everyone that is not in Plone GitHub organization.
=> Avoid using global variables

news/+cleanup.bugfix, shared-workflows/tests.yml
This `shared-workflows` folder was used when the idea was to use GitHub organization wide workflows, but the idea turned out not to be so great, nor useful outside the GitHub Plone organization.
They were left there, so, before deleting them, let's make them crash, to see if there is anyone out there still using them, hopefully not 🤞🏾
=> Deprecate old GHA workflows

config/default/gitlab-ci.yml.j2, config/default/tox.ini.j2
When using GitLab, report the tests that did run.
As a bonus, report also the coverage percentage to GitLab so it can be used on the UI.
We need a counterpart for those for GitHub, but we can still get this merged, and as time/need allows, get those as well.
There has to be some GHA that gets a junit report and there's plenty regarding coverage as well.
=> Junit reports

config/README.md, config/config-package.py, news/+ignore2.bugfix
On the original `zopefoundation/meta` they had this option as `True` by default, as the idea is to ensure that whenever major changes (new python version, etc) are applied to a template folder (here in `plone/meta` only `config/default`) all repositories listed in `packages.txt` would be updated.
Here in `plone/meta` we departed from that idea and instead we use this tool as a generic configuration tool for any repository. It is not only meant for plone packages only.
Thus, it does not make sense to track packages by default.
=> No track by default

.github/workflows/test.yml, config/README.md, config/config-package.py, config/default/meta.yml.j2, news/210.feature
Part of #210 
Runs tests for a given package with any list of python packages provided by the package itself, or, with the defaults provided by the workflow defined here in `plone/meta`.
This is only 1 of the 3 axis mentioned in #210 (OS / Plone / python), though probably the most important and the easiest 😅 
@1letter
=> GHA: run tests with multiple python versions

.github/workflows/test.yml
Packages that use gocept.pytestlayer are broken then, because it is not compatible. It is being replaced by zope.pytestlayer.
Sample error:
https://github.com/plone/plone.releaser/actions/runs/9086068912/job/24970903122 ModuleNotFoundError: No module named 'imp'
=> By default do not test on 3.12.

config/config-package.py, config/default/tox.ini.j2
For cases where the folder name is distinct from the package_name (i.e.: pytest-plone / pytest_plone)
=> Tox: Allow explicitly setting the package_name

config/default/gitignore.j2
These files are generated when we run `tox -e circular`
=> Ignore files forest.dot and forest.json

news/248.bugfix, src/plone/meta/config_package.py
Part of #248 
If we are not meant to use a git checkout but an actual version, record that on `.meta.toml` when configuring/updating repositories.
It needs #250 to get merged first
=> Use package version
